// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: views.sql

package sqlc

import (
	"context"
)

const getViewCount = `-- name: GetViewCount :one
SELECT
    count
FROM
    views
WHERE
    post_slug = $1
`

func (q *Queries) GetViewCount(ctx context.Context, postSlug string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getViewCount, postSlug)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const incrementView = `-- name: IncrementView :exec
INSERT INTO
    views (post_slug, count)
VALUES
    ($1, 1)
ON CONFLICT (post_slug) DO UPDATE
SET
    count = views.count + 1
`

func (q *Queries) IncrementView(ctx context.Context, postSlug string) error {
	_, err := q.db.ExecContext(ctx, incrementView, postSlug)
	return err
}
