// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: likes.sql

package sqlc

import (
	"context"
	"time"
)

const countLikesByPostSlug = `-- name: CountLikesByPostSlug :one
SELECT
    COUNT(*) FROM likes
WHERE
    post_slug = $1
`

func (q *Queries) CountLikesByPostSlug(ctx context.Context, postSlug string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countLikesByPostSlug, postSlug)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLike = `-- name: CreateLike :exec
INSERT INTO
    likes (id, post_slug, owner_id, created_at)
VALUES
    ($1, $2, $3, $4)
`

type CreateLikeParams struct {
	ID        string
	PostSlug  string
	OwnerID   string
	CreatedAt time.Time
}

func (q *Queries) CreateLike(ctx context.Context, arg CreateLikeParams) error {
	_, err := q.db.ExecContext(ctx, createLike,
		arg.ID,
		arg.PostSlug,
		arg.OwnerID,
		arg.CreatedAt,
	)
	return err
}

const deleteLike = `-- name: DeleteLike :exec
DELETE FROM likes
WHERE
    post_slug = $1
    AND owner_id = $2
`

type DeleteLikeParams struct {
	PostSlug string
	OwnerID  string
}

func (q *Queries) DeleteLike(ctx context.Context, arg DeleteLikeParams) error {
	_, err := q.db.ExecContext(ctx, deleteLike, arg.PostSlug, arg.OwnerID)
	return err
}

const likeExistsByPostSlugAndOwnerID = `-- name: LikeExistsByPostSlugAndOwnerID :one
SELECT
    EXISTS (
        SELECT 1 FROM likes
        WHERE post_slug = $1 AND owner_id = $2
    )
`

type LikeExistsByPostSlugAndOwnerIDParams struct {
	PostSlug string
	OwnerID  string
}

func (q *Queries) LikeExistsByPostSlugAndOwnerID(ctx context.Context, arg LikeExistsByPostSlugAndOwnerIDParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, likeExistsByPostSlugAndOwnerID, arg.PostSlug, arg.OwnerID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
