// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: comments.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createComment = `-- name: CreateComment :exec
INSERT INTO
    comments (id, post_slug, owner_id, content, parent_id, created_at, updated_at)
VALUES
    ($1, $2, $3, $4, $5, $6, $7)
`

type CreateCommentParams struct {
	ID        string
	PostSlug  string
	OwnerID   string
	Content   string
	ParentID  sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) error {
	_, err := q.db.ExecContext(ctx, createComment,
		arg.ID,
		arg.PostSlug,
		arg.OwnerID,
		arg.Content,
		arg.ParentID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const findCommentByID = `-- name: FindCommentByID :one
SELECT
    id, post_slug, owner_id, content, parent_id, created_at, updated_at, deleted_at
FROM
    comments
WHERE
    id = $1
`

func (q *Queries) FindCommentByID(ctx context.Context, id string) (Comment, error) {
	row := q.db.QueryRowContext(ctx, findCommentByID, id)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.PostSlug,
		&i.OwnerID,
		&i.Content,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const findCommentsByPostSlug = `-- name: FindCommentsByPostSlug :many
SELECT
    id, post_slug, owner_id, content, parent_id, created_at, updated_at, deleted_at
FROM
    comments
WHERE
    post_slug = $1
    AND deleted_at IS NULL
ORDER BY
    created_at ASC
`

func (q *Queries) FindCommentsByPostSlug(ctx context.Context, postSlug string) ([]Comment, error) {
	rows, err := q.db.QueryContext(ctx, findCommentsByPostSlug, postSlug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Comment
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.PostSlug,
			&i.OwnerID,
			&i.Content,
			&i.ParentID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateComment = `-- name: UpdateComment :exec
UPDATE comments
SET
    content = $2,
    updated_at = $3,
    deleted_at = $4
WHERE
    id = $1
`

type UpdateCommentParams struct {
	ID        string
	Content   string
	UpdatedAt time.Time
	DeletedAt sql.NullTime
}

func (q *Queries) UpdateComment(ctx context.Context, arg UpdateCommentParams) error {
	_, err := q.db.ExecContext(ctx, updateComment,
		arg.ID,
		arg.Content,
		arg.UpdatedAt,
		arg.DeletedAt,
	)
	return err
}
