// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"time"
)

type Comment struct {
	ID        string
	PostSlug  string
	OwnerID   string
	Content   string
	ParentID  sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
}

type Credential struct {
	ID           string
	OwnerID      string
	Email        string
	PasswordHash []byte
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type Like struct {
	ID        string
	PostSlug  string
	OwnerID   string
	CreatedAt time.Time
}

type RefreshToken struct {
	ID        string
	OwnerID   string
	TokenHash []byte
	ExpiresAt time.Time
	RevokedAt sql.NullTime
	CreatedAt time.Time
}

type User struct {
	ID        string
	CreatedAt time.Time
}

type View struct {
	PostSlug string
	Count    int64
}
